---
name: 'ansible-lint'
on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - 'main'
  workflow_dispatch: {}

permissions:
  contents: 'read'

jobs:
  build:
    name: 'Ansible Lint'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Harden Runner'
        uses: 'step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6' # v2.8.1
        with:
          disable-sudo: true
          egress-policy: 'block'
          allowed-endpoints: >-
            files.pythonhosted.org:443
            github.com:443
            pypi.org:443
            raw.githubusercontent.com:443

      - name: 'Checkout code'
        uses: 'actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332' # v4.1.7

      - name: 'Run ansible-lint'
        uses: 'ansible/ansible-lint@b4018c22f8fe8371bd6845d0cd62cebea54ce012' # v24.6.1
...
